config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'courses#index'
  resources :courses do
    resources :orders, only: [:create, :destroy] do
      collection do
        get :favorite
      end
    end
    collection do
      get :search
    end
    
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'プログラミング' },
    { id: 3, name: 'ゲーム' },
    { id: 4, name: 'イラスト' },
    { id: 5, name: '音楽' },
    { id: 6, name: 'エクササイズ' },
    { id: 7, name: 'スポーツ' },
    { id: 8, name: '趣味' },
    { id: 9, name: '教育・教養' },
    { id: 10, name: 'ビジネススキル' },
    { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_one_attached :image
  belongs_to :category
  belongs_to :hour
  belongs_to :machine
  belongs_to :time_zone

  def self.search(search)
    if search != ''
      Course.where('text_1 LIKE(?)', "%#{search}%").order('created_at DESC')
    else
      Course.all.order('created_at DESC')
    end
  end

  with_options presence: true do
    validates :title
    validates :text_1
  end
  with_options numericality: { other_than: 1, message: "can't be blank" } do
    validates :category_id
    validates :hour_id
    validates :machine_id
    validates :time_zone_id
  end
  validates :price, presence: true, format: { with: /\A[0-9]+\z/, allow_blank: true },
                    numericality: {
                      allow_blank: true,
                      only_integer: true,
                      greater_than_or_equal_to: 100, less_than_or_equal_to: 99_999
                    }
end

app/models/hour.rb
class Hour < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '0.5時間未満' },
    { id: 3, name: '0.5~1時間' },
    { id: 4, name: '1~2時間' },
    { id: 5, name: '2時間以上' },
    { id: 6, name: '1日以上' }
  ]
  include ActiveHash::Associations
  has_many :courses
end

app/models/machine.rb
class Machine < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'PC' },
    { id: 3, name: 'PC(Windows対応のみ)' },
    { id: 4, name: 'Macbook' },
    { id: 5, name: 'タブレット' },
    { id: 6, name: 'ペンタブ' },
    { id: 7, name: 'スマートフォン' },
    { id: 8, name: 'Android' },
    { id: 9, name: 'iPhone' },
    { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :courses
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :user_id, uniqueness: { scope: :course_id }
end

app/models/time_zone.rb
class TimeZone < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '早朝' },
    { id: 3, name: '午前' },
    { id: 4, name: '午後' },
    { id: 5, name: '夕方' },
    { id: 6, name: '午前0時前' },
    { id: 7, name: '午前0時以降' }
  ]
  include ActiveHash::Associations
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :orders
  has_many :ord_courses, through: :orders, source: :course

  def like(course)
    orders.find_or_create_by(course_id: course.id)
  end

  def unlike(course)
    order = orders.find_by(course_id: course.id)
    order.destroy if order
  end

  def like?(course)
    ord_courses.include?(course)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください', allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_params, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @courses = Course.all.order('created_at DESC')
    @course1 = Course.where(category_id: 2).order('created_at DESC')
    @course2 = Course.where(category_id: 3).order('created_at DESC')
    @course3 = Course.where(category_id: 4).order('created_at DESC')
    @course4 = Course.where(category_id: 5).order('created_at DESC')
    @course5 = Course.where(category_id: 6).order('created_at DESC')
    @course6 = Course.where(category_id: 7).order('created_at DESC')
    @course7 = Course.where(category_id: 8).order('created_at DESC')
    @course8 = Course.where(category_id: 9).order('created_at DESC')
    @course9 = Course.where(category_id: 10).order('created_at DESC')
    @course10 = Course.where(category_id: 11).order('created_at DESC')
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to "/users/#{current_user.id}"
    else
      render :new
    end
  end

  def show
    @order = Order.find_by(user_id: current_user.id, course_id: @course.id)
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course.id)
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to "/users/#{current_user.id}"
  end

  def search
    @courses = Course.search(params[:keyword])
  end

  private

  def course_params
    params.require(:course).permit(:title, :category_id, :text_1, :text_2, :text_3, :text_4, :hour_id, :machine_id,
                                   :other_machine, :time_zone_id, :price, :image).merge(user_id: current_user.id)
  end

  def find_params
    @course = Course.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @course.user_id
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :favorite]
  before_action :not_seller, only: [:create, :destroy]
  before_action :not_order, only: :favorite

  def create
    course = Course.find(params[:course_id])
    current_user.like(course)
    redirect_back fallback_location: root_path, success: '申請しました'
  end

  def destroy
    course = current_user.orders.find_by(params[:id]).course
    current_user.unlike(course)
    redirect_back fallback_location: root_path, success: '申請を取り消しました'
  end

  def favorite
    @course = Course.find(params[:course_id])
    order_course = Order.where(course_id: @course.id)
    orders = order_course.pluck(:user_id)
    @order_users = User.find(orders)
  end

  private

  def not_seller
    course = Course.find(params[:course_id])
    redirect_to root_path if current_user.id == course.user_id
  end

  def not_order
    course = Course.find(params[:course_id])
    redirect_to root_path unless current_user.id == course.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :not_current_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @courses = @user.courses
    if user_signed_in?
      orders = Order.where(user_id: current_user.id).pluck(:course_id)
      @order_courses = Course.find(orders)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :profile)
  end

  def not_current_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user.id = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/courses/_course.html.erb
        <li class='course-one-list'>
          <div class='course-img-content'>
          <%= link_to course_path(course.id) do %>
            <%if course.image.present?%>
              <%= image_tag course.image, class: "course-img" %>
            <%else%>
              <%= image_tag "22116720_s.jpg", class: "course-img" %>
            <% end %>
          <% end %>
          </div>
          <div class='course-info'>
            <ul>
              <li class="course-title"><%= link_to "#{course.title}", course_path(course.id), class: :course_title_link %></li>
              <li><%= link_to "#{course.price}円", course_path(course.id), class: :course_price_link %></li>
              <li><%= link_to "開講者: #{course.user.nickname}さん", "/users/#{course.user.id}", class: :course_user %></li>
            </ul>
          </div>
        </li>

app/views/courses/_dummy.html.erb
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "22116720_s.jpg", class: "course-img" %>
          <div class='course-info'>
            <h3 class='course-title'>
              講座を開設してみよう！
            </h3>
            <div class='course-price'>
              <span>99999円</span>
            </div>
          </div>
          <% end %>
        </li>

app/views/courses/_form.html.erb
  <div class="courses-sell-main">
    <h2 class="courses-sell-title">講座内容を入力</h2>
    <%= form_with model: @course, local: true do |f| %>

    <%#エラー表示%>
    <%= render 'shared/error_messages', model: f.object %>
    <%#/エラー表示%>
    
    <%# 講座内容 %>
    <div class="field">
      <div class="side-text">
        講座イメージ画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"course-image" %>
      </div>
    </div>

    <div class="field">
      <div class="side-text">
        講座名(わかりやすく講座紹介)
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"course-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>

    <div class="field">
      <div class="side-text">
        講座内容(一つ以上記入してください)
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text_1, class:"items-text", id:"item-info-1", placeholder:"必須 1000文字以内でわかりやすく記述しましょう" ,rows:"4" ,maxlength:"1000" %>
      <%= f.text_area :text_2, class:"items-text", id:"item-info-2", placeholder:" 1000文字以内でわかりやすく記述しましょう" ,rows:"4" ,maxlength:"1000" %>
      <%= f.text_area :text_3, class:"items-text", id:"item-info-3", placeholder:" 1000文字以内でわかりやすく記述しましょう" ,rows:"4" ,maxlength:"1000" %>
      <%= f.text_area :text_4, class:"items-text", id:"item-info-4", placeholder:" 1000文字以内でわかりやすく記述しましょう" ,rows:"4" ,maxlength:"1000" %>
    </div>

    <div class="field">
      <div class="side-text">
        カテゴリー
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"course-category"}) %>
    </div>

    <div class="field">
      <div class="side-text">
        受講時間
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:hour_id, Hour.all, :id, :name, {}, {class:"select-box", id:"course-hour"}) %>
    </div>

    <div class="field">
      <div class="side-text">
        受講に必要な機材
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:machine_id, Machine.all, :id, :name, {}, {class:"select-box", id:"course-machine"}) %>
    </div>

    <div class="field">
      <div class="side-text">
        その他に選んだ場合、また追加の機材がある場合入力してください
      </div>
      <%= f.text_field :other_machine, class:"items-text", id:"other-machine", placeholder:"機材名（40文字まで)", maxlength:"40" %>
    </div>

    <div class="field">
      <div class="side-text">
        講義できる時間帯
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:time_zone_id, TimeZone.all, :id, :name, {}, {class:"select-box", id:"course-time-zone"}) %>
    </div>

    <div class="field">
      <div class="side-text">
        講座料金(¥100〜99,999)
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :price, class:"price-input", id:"course-price", placeholder:"例）300" %><span> 円</span>
    </div>
    <%# /講座内容 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "保存する" ,class:"sell-btn" %>
    </div>
    <div class="back-root">
      <%=link_to 'トップページに戻る', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>

app/views/courses/edit.html.erb
<%= render "shared/second-header" %>

<div class="courses-sell-contents">
  <%=render partial: "form"%>
</div>

<%= render "shared/footer" %>

app/views/courses/index.html.erb
<%= render "shared/header" %>

<div class="main">

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <div class="service-contents">
      <h2 class='service-title'>
        あなたが学び、あなたが教える
      </h2>
      <p class='service-explain'>
        ~夢を叶えるための一歩めをここで踏み出そう~
      </p>
    </div>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の帯部分  %>

  <%# 講座一覧%>
  <div class="course-content course-top" >
    <div class="category-title" >
      最新投稿一覧
    </div>
    <ul class='course-lists'>
      <%if @courses.length > 0%>
        <%= render partial: 'course', collection: @courses%>
      <% else %>
        <%= render "dummy" %>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      プログラミング
    </div>
    <ul class='course-lists'>
      <%if @course1.length > 0%>
        <%= render partial: 'course', collection: @course1%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      ゲーム
    </div>
    <ul class='course-lists'>
      <%if @course2.length > 0%>
        <%= render partial: 'course', collection: @course2%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      イラスト
    </div>
    <ul class='course-lists'>
      <%if @course3.length > 0%>
        <%= render partial: 'course', collection: @course3%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      音楽
    </div>
    <ul class='course-lists'>
      <%if @course4.length > 0%>
        <%= render partial: 'course', collection: @course4%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      エクササイズ
    </div>
    <ul class='course-lists'>
      <%if @course5.length > 0%>
        <%= render partial: 'course', collection: @course5%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      スポーツ
    </div>
    <ul class='course-lists'>
      <%if @course6.length > 0%>
        <%= render partial: 'course', collection: @course6%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      趣味
    </div>
    <ul class='course-lists'>
      <%if @course7.length > 0%>
        <%= render partial: 'course', collection: @course7%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      教育・教養
    </div>
    <ul class='course-lists'>
      <%if @course8.length > 0%>
        <%= render partial: 'course', collection: @course8%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      ビジネススキル
    </div>
    <ul class='course-lists'>
      <%if @course9.length > 0%>
        <%= render partial: 'course', collection: @course9%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>

  <div class="course-content">
    <div class="category-title" >
      その他
    </div>
    <ul class='course-lists'>
      <%if @course10.length > 0%>
        <%= render partial: 'course', collection: @course10%>
      <% else %>
        <div class="not-course">
          受講できる講座はありません
        </div>
      <% end %>
    </ul>
  </div>
  <%# /講座一覧%>
</div>

<%= render "shared/footer" %>

app/views/courses/new.html.erb
<%= render "shared/second-header" %>

<div class="courses-sell-contents">
  <%=render partial: "form"%>
</div>

<%= render "shared/footer" %>

app/views/courses/search.html.erb
<%= render "shared/header" %>

<div class="course-content">
  <div class="category-title" >
      検索結果
  </div>
  <% if @courses.present? %>
    <ul class='course-lists'>
      <%= render partial: 'course', collection: @courses%>
    </ul>
  <% else %>
    一致するものは見つかりませんでした
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/courses/show.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="course-main-info">
  <%#講座内容%>
    <div class="course-main-content">

      <div class="course-title-content">
        <%= @course.title %>
      </div>

      <div class="course-detail-info">
        <div class="item-img-content">
        <%if @course.image.present?%>
          <%= image_tag @course.image ,class:"course-box-img" %>
        <% else %>
          <%= image_tag "22116720_s.jpg", class: "course-box-img" %>
        <%end%>
        </div>

        <div class="course-detail">
          <div class="course-detail-content">
            <span class="detail-title">カテゴリー : </span><span class="detail-message"><%=@course.category.name%></span>
          </div>
          <div class="course-detail-content">
            <span class="detail-title">開講者 : </span><%= link_to @course.user.nickname, "/users/#{@course.user.id}", class: :course_info_user %>
          </div>
          <div class="course-detail-content">
            <span class="detail-title">講習時間 : </span><span class="detail-message"><%=@course.hour.name%></span>
          </div>
          <div class="course-detail-content">
          <%if @course.machine.id < 11%>
            <span class="detail-title">必要になる機材 : </span><span class="detail-message"><%=@course.machine.name%></span>
            <%if @course.other_machine.present?%>
            <span class="detail-message"> , <%=@course.other_machine%></span>
            <% end %>
          <%else%>
            <span class="detail-title">必要になる機材 : </span><span class="detail-message"><%=@course.other_machine%></span>
          <% end %>
          </div>
          <div class="course-detail-content">
            <span class="detail-title">受講可能な時間帯 : </span><span class="detail-message"><%=@course.time_zone.name%></span>
          </div>
        </div>
      </div>

      <div class="course-price-content">
        <span class="price-number">¥<%=@course.price%></span>
      </div>
    </div>

    <%if current_user.id == @course.user_id %>
      <div class="order-group">
        <%= link_to "受講希望者リスト", "/courses/#{@course.id}/orders/favorite", method: :get, class: "course-order-btn" %>
      </div>
    <% end %>

    <div class="course-sub-content">
      <p class="text-title">講座内容</p>
      <p class="text-message">・<%= safe_join(@course.text_1.split("\n"),tag(:br)) %></p>
      <%if @course.text_2.present?%>
      <p class="text-message">・<%= safe_join(@course.text_2.split("\n"),tag(:br)) %></p>
      <% end %>
      <%if @course.text_3.present?%>
      <p class="text-message">・<%= safe_join(@course.text_3.split("\n"),tag(:br)) %></p>
      <% end %>
      <%if @course.text_4.present?%>
      <p class="text-message">・<%= safe_join(@course.text_4.split("\n"),tag(:br)) %></p>
      <% end %>
    </div>

    <%#/講座内容%>

    <%#編集or受講ボタン%>
    <div class="bottom-course-btn">
      <% if user_signed_in? %>
        <% if current_user.id == @course.user_id%>
          <%= link_to "講座の編集", edit_course_path(@course.id), method: :get, class: "course-btn" %>
          <p class="or-text">or</p>
          <%= link_to "講座を削除", course_path(@course.id), method: :delete, class:"course-btn", id: "destroy-btn" %>
        <% else %>
          <% unless current_user.like?(@course) %>
            <%= link_to "受講を希望する", "/courses/#{@course.id}/orders", method: :post ,class:"course-btn"%>
          <% else %>
            <%= link_to "受講希望を取り消す", "/courses/#{@course.id}/orders/#{@order.id}", method: :delete ,class:"course-btn"%>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <%#/編集or受講ボタン%>

  </div>

</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>StepOut</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'  %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/favorite.html.erb
<%= render "shared/header" %>

<div class="orders-lists">
  <h2 class="order-title">
    受講希望者一覧
  </h2>
  <%if @order_users.present?%>
  <ul class="order-users-lists">
    <% @order_users.each do |order_user| %>
      <li class="order-users-list">
        <%= link_to order_user.nickname, "/users/#{order_user.id}", class: :order_user %>
      </li>
    <% end %>
  </ul>
  <% else %>
    <p class="none-order">受講予定者はいません</p>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='fotter'>
  <div class='fotter-text-wrap'>
    <p class='fotter-text'>お問い合わせ</p>
    <p class='fotter-text'>規約</p>
    <p class='fotter-text'>ヘルプとサポート</p>
    <p>© stepout</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-header'>
  <div class="app-title">
    <%= link_to image_tag("step-out.logo.png", class:"stepout-icon"), "/" %>
  </div>
  <div class='search-bar-contents'>
    <%= form_with(url: search_courses_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードから探す", class: "input-box" %>
      <%= form.submit class: "search-icon" %>
    <% end %>
  </div>
  <div class='log-status'>
    <ul class='log-lists'>
    <%if user_signed_in? %>
      <li><%= link_to "ようこそ #{current_user.nickname} さん", "/users/#{current_user.id}", class: "user-nickname" %></li>
      <li><%= link_to '講座を開く', new_course_path, class: "course-up" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "user-nickname" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "course-up" %></li>
    <% end%>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class="second-header">
  <%= link_to image_tag('step-out.logo.png' , size: '185x50'), "/" %>
</header>

app/views/users/edit.html.erb
<%= render "shared/second-header" %>

<div class="courses-sell-contents">
  <div class="courses-sell-main">
    <h2 class='courses-sell-title'>プロフィール編集</h2>
    <%= form_with model: @user, class: 'registration-main', local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <div class="side-text">
          ニックネーム
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :nickname, class:"items-text", id:"nickname", placeholder:"例) ステップ太郎", maxlength:"40" %>
      </div>
      
      <div class="field">
        <div class="side-text">
          プロフィール
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :profile, class:"items-text", id:"profile", placeholder:"例) 〇〇です。よろしくお願いします！",rows:"7" ,maxlength:"1000" %>
      </div>
      
      <div class="sell-btn-contents">
        <%= f.submit "編集する" ,class:"sell-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>


<div class="main">
  <div class="user-info">
      <h2 class="page-heading">
        <%= "#{@user.nickname}"%>
      </h2>
      <div class="user-profile">
      <% if @user.profile.present? %>
        <%= safe_join(@user.profile.split("\n"),tag(:br)) %>
      <% end %>
      </div>
      <div class="user-edit">
      <%if user_signed_in?%>
        <% if current_user.id == @user.id %> 
          <%= link_to "プロフィール編集", "/users/#{current_user.id}/edit", class: "user-edits" %>
        <% end %>
      <% end %>
      </div>
  </div>

  <%#開講した講座一覧%>
  <div class="course-content">
    <div class="category-title" >
      <%= "#{@user.nickname}さんの講座"%>
    </div>
    <ul class='course-lists'>
      <%if @courses.length > 0%>
        <%= render partial: 'courses/course', collection: @courses%> 
      <% else %>
        <div class="not-course">
          <%= render "courses/dummy" %>
        </div>
      <% end %>
    </ul>
  </div>
  <%#/開講した講座一覧%>

  <%#受講希望した講座一覧%>
  <%if user_signed_in?%>
    <%if current_user.id == @user.id  %>
    <div class="course-content">
      <div class="category-title" >
        受講希望している講座
      </div>
      <ul class='course-lists'>
        <%if current_user.orders.present?%>
          <%= render partial: 'courses/course', collection: @order_courses%> 
        <% else %>
          <div class="not-order">
            現在受講を希望している講座はありません
          </div>
        <% end %>
      </ul>
    </div>
    <% end %>
  <% end %>
  <%#/受講希望した講座一覧%>
</div>

<%= render "shared/footer" %>